require "http/client"
require "json"

KEY = "eyJ4NXQiOiJaV05sTURNNE56SmpZelZrT1dFNU16RTFNalF5TTJaaE5XSm1ORE0zWkRVMk9HRXdOVGxqWVRjNE1tWTNPRGcwWW1JeFlqSTFPVGMzTjJWallqZzRNdyIsImtpZCI6IlpXTmxNRE00TnpKall6VmtPV0U1TXpFMU1qUXlNMlpoTldKbU5ETTNaRFUyT0dFd05UbGpZVGM0TW1ZM09EZzBZbUl4WWpJMU9UYzNOMlZqWWpnNE13X1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJ0NGRTOVNCblQwenBZVEd4NThiUk1xTHY2eEVhIiwiYXV0IjoiQVBQTElDQVRJT04iLCJiaW5kaW5nX3R5cGUiOiJyZXF1ZXN0IiwiaXNzIjoiaHR0cHM6XC9cL2V4dC1hcGkudmFzdHRyYWZpay5zZVwvdG9rZW4iLCJ0aWVySW5mbyI6eyJVbmxpbWl0ZWQiOnsidGllclF1b3RhVHlwZSI6InJlcXVlc3RDb3VudCIsImdyYXBoUUxNYXhDb21wbGV4aXR5IjowLCJncmFwaFFMTWF4RGVwdGgiOjAsInN0b3BPblF1b3RhUmVhY2giOnRydWUsInNwaWtlQXJyZXN0TGltaXQiOjAsInNwaWtlQXJyZXN0VW5pdCI6bnVsbH19LCJrZXl0eXBlIjoiUFJPRFVDVElPTiIsInN1YnNjcmliZWRBUElzIjpbeyJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjoiY2FyYm9uLnN1cGVyIiwibmFtZSI6ImFwaTAwMTMtcHIiLCJjb250ZXh0IjoiXC9wclwvdjQiLCJwdWJsaXNoZXIiOiJhZG1pbiIsInZlcnNpb24iOiJ2NCIsInN1YnNjcmlwdGlvblRpZXIiOiJVbmxpbWl0ZWQifSx7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoiYXBpMDA1OS1nZW8iLCJjb250ZXh0IjoiXC9nZW9cL3YyIiwicHVibGlzaGVyIjoiYWRtaW4iLCJ2ZXJzaW9uIjoidjIiLCJzdWJzY3JpcHRpb25UaWVyIjoiVW5saW1pdGVkIn1dLCJhdWQiOiJodHRwczpcL1wvZXh0LWFwaS52YXN0dHJhZmlrLnNlIiwibmJmIjoxNzAzNzc3NzQ3LCJhcHBsaWNhdGlvbiI6eyJvd25lciI6InQ0ZFM5U0JuVDB6cFlUR3g1OGJSTXFMdjZ4RWEiLCJ0aWVyUXVvdGFUeXBlIjpudWxsLCJ0aWVyIjoiVW5saW1pdGVkIiwibmFtZSI6IlJlc2VwbGFuZXJhcmVuXzIiLCJpZCI6MTkyOSwidXVpZCI6ImM0YmM5Y2ZkLWZiOWUtNDRmNC05ZjIyLTQ1MTQ3NzZjNGQyOCJ9LCJhenAiOiJ0NGRTOVNCblQwenBZVEd4NThiUk1xTHY2eEVhIiwic2NvcGUiOiJhcGltOnN1YnNjcmliZSIsImV4cCI6MTcwMzg2NDE0NywiaWF0IjoxNzAzNzc3NzQ3LCJiaW5kaW5nX3JlZiI6ImI3NDY2MzUxODllZGZmMTE3OGRlMjFjOTc4NzgzZDMyIiwianRpIjoiZTM0Y2YzNDEtMTllZi00YzJhLTg4NDEtZTYxYjQ0MjkyZTdlIn0.Jr__BPIgQ3o21WE4UcawM5L3IRw_oQge73OJKL5kaYfvWwoADT0LbioocpV9QMr3c4Dkp2tsHxhO87mvze5IUC8KYaD5osD5BxuVLjiSuvHRdFhaTQAkZuOjOgJBy8HKyGby8Hu288LMhs0ALUTAYCCRe6uhicp4DNLaZ42XCIqZFwQoZ95rxC14yFK1NzdsfbJ6b-tlZNM7wxGBxTM6dl5XoyIYQszJwBvPazhuCwLDLUuOu8ue39yisbRpWbzkNtPpYELcRhzWTqKhWXnomMD6Y4f-VEBiBfpy1EObu6iS4BKSOmavPxVAkZJAEWgaaD3pQOI6qByU8-v-7cgNkw"

class Api::Västraffik::ShowDetailed < ApiAction

  HEADER = HTTP::Headers{"Authorization" => "Bearer #{KEY}", "accept" => "application/json"} 

  include Api::Auth::SkipRequireAuthToken

  post "/api/vastraffik/route" do
    id = params.from_json["detailsReference"].as_s
    uri = URI::Params.encode({"includes" => ["ticketsuggestions", "triplegcoordinates", "validzones", "servicejourneycalls", "servicejourneycoordinates", "links", "occupancy"] })
    route = URI.new("https", "ext-api.vasttrafik.se", path: "/pr/v4/journeys/#{id}/details", query: uri)
    response = HTTP::Client.get(route, HEADER)
    raw_json response.body
  end
end